// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Fable2CSharp")]
[assembly: AssemblyProductAttribute("fs2cs")]
[assembly: AssemblyDescriptionAttribute("F# to C# Transpiler")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
